---

- block:
    - validate:
        schema:
          type: object
          properties:
            command:
              type: string
              enum:
                - phase_1
                - phase_2
          required:
            - command
        instance: "{{ hardened_ubuntu }}"

    - include_tasks: '{{ hardened_ubuntu.command }}.yml'
  tags:
    - hardened_ubuntu
