---

- block:
  - validate:
      schema:
        type: object
        additionalProperties: no
        properties:
          fail2ban_ban_time:
            type: string
            pattern: ^[0-9]+$
            default: 600
          fail2ban_find_time:
            type: string
            pattern: ^[0-9]+$
            default: 600
          fail2ban_ignored_ips:
            type: array
            items:
              type: string
              format: ipv4
            default: []
          fail2ban_max_retries:
            type: string
            pattern: ^[0-9]+$
            default: 5
          fail2ban_slack_webhook_url:
            type: string
            format: uri
          os_swap_device:
            type: string
          ssh_allowed_networks:
            type: array
            items:
              type: string
              format: ipv4
            minLength: 1
            default:
              - 0.0.0.0/0
          ssh_allowed_users:
            type: array
            items:
              type: string
            minLength: 1
            default:
              - ubuntu
          ssh_agent_forwarding_enabled:
            type: boolean
            default: no
          ssh_authorized_keys:
            type: object
            patternProperties:
              "^[A-Za-z0-9_]+$":
                type: array
                items:
                  type: string
                minLength: 1
          ssh_exclusive_keys_enabled:
            type: boolean
            default: no
          ssh_sftp_enabled:
            type: boolean
            default: yes
          ssh_tun_device_forwarding_enabled:
            type: boolean
            default: no
        required:
          - fail2ban_ban_time
          - fail2ban_ignored_ips
          - ssh_allowed_networks
          - ssh_allowed_users
          - ssh_agent_forwarding_enabled
          - ssh_exclusive_keys_enabled
          - ssh_sftp_enabled
          - ssh_tun_device_forwarding_enabled
      instance: "{{ hardened_ubuntu | default({}) }}"
    register: hardened_ubuntu_validated

  - set_fact:
      hardened_ubuntu_v: "{{ hardened_ubuntu_validated.result }}"

  - name: "Upgrade packages"
    import_role:
      name: bedrock.os
    vars:
      os:
        command: upgrade_packages
        update_cache: yes

  - name: "Authorize SSH keys"
    import_role:
      name: bedrock.ssh
    vars:
      ssh:
        command: authorize_keys
        authorized_keys: "{{ hardened_ubuntu_v.ssh_authorized_keys }}"
        exclusive: "{{ hardened_ubuntu_v.ssh_exclusive_keys_enabled }}"
    when: "'ssh_authorized_keys' in hardened_ubuntu_v"

  - name: 'Harden SSH'
    import_role:
      name: bedrock.ssh
    vars:
      ssh:
        command: harden
        agent_forwarding_enabled: "{{ hardened_ubuntu_v.ssh_agent_forwarding_enabled }}"
        allowed_users: "{{ hardened_ubuntu_v.ssh_allowed_users }}"
        sftp_enabled: "{{ hardened_ubuntu_v.ssh_sftp_enabled }}"
        tun_device_forwarding_enabled: "{{ hardened_ubuntu_v.ssh_tun_device_forwarding_enabled }}"

  - name: 'Install UFW'
    import_role:
      name: bedrock.os
    vars:
      os:
        command: install_ufw
        ssh_allowed_networks: "{{ hardened_ubuntu_v.ssh_allowed_networks }}"

  - name: 'Add SSH jail to fail2ban'
    import_role:
      name: bedrock.fail2ban
    vars:
      fail2ban:
        command: create_sshd_jail
        ban_time: "{{ hardened_ubuntu_v.fail2ban_ban_time }}"
        find_time: "{{ hardened_ubuntu_v.fail2ban_find_time }}"
        ignored_ips: "{{ hardened_ubuntu_v.fail2ban_ignored_ips }}"
        max_retries: "{{ hardened_ubuntu_v.fail2ban_max_retries }}"
        slack_webhook_url: "{{ hardened_ubuntu_v.fail2ban_slack_webhook_url | default(None) }}"

  - name: "Configure swap space"
    import_role:
      name: bedrock.os
    vars:
      os:
        command: swap
        device: "{{ hardened_ubuntu_v.os_swap_device }}"
    when: "('os_swap_device' in hardened_ubuntu_v) and (hardened_ubuntu_v.os_swap_device != '')"

  - name: "Reboot the machine if necessary"
    import_role:
      name: bedrock.os
    vars:
      os:
        command: reboot_if_required
  tags:
    - hardened_ubuntu_phase_2